version: "2.1"

services:
    redis:
        image: "redis:alpine"
        ports:
            - 6379:6379
    app:
        build: .
        ports:
            - 8000:8000
        restart: always
        depends_on:
            - redis